twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: 'Le Blog de Batman Qui Rit'

when@test:
    twig:
        strict_variables: true
